#!/bin/bash
set -eu

## Load a wordpress dumped db, obtain credentials from wp-config.php
## if DB_TABLE environment variable set = load only this table
## Used in maintaining a development and production environment for Wordpress
## deployments
## Author Andy O'Neill <oneill@energyhub.net>

function check_dump_file {
    if [ ! -e "$DB_DUMP" ]; then
        echo "DB file to load not found: $DB_DUMP"
        echo "Run from your wordpress directory"
        echo "Usage loaddb"
        exit 1
    fi
}

if [ ! -e wp-config.php ]; then
    echo "wp-config.php not found"
    echo "Run from your wordpress directory"
    echo "Usage dumpdb"
    exit 1
fi

# Get the parameters of the db to load into from wp_config.php
DB_NAME=$(      grep DB_NAME        wp-config.php  | awk -F "'" '{print $4}')
DB_USER=$(      grep DB_USER        wp-config.php  | awk -F "'" '{print $4}')
DB_PASSWORD=$(  grep DB_PASSWORD    wp-config.php  | awk -F "'" '{print $4}')
DB_HOST=$(      grep DB_HOST        wp-config.php  | awk -F "'" '{print $4}' |  awk -F ":" '{print $1}' )
DB_PORT=$(      grep DB_HOST        wp-config.php  | awk -F "'" '{print $4}' |  awk -F ":" '{print $2}' )
echo "DB_NAME=[$DB_NAME]"
echo "DB_USER=[$DB_USER]"
echo "DB_PASSWORD=[$DB_PASSWORD]"
echo "DB_HOST=[$DB_HOST]"
echo "DB_PORT=[$DB_PORT]"
#TODO add check for port presence

DATE=$(date +%Y-%m-%d-%H%M)

#if DB_TABLE set => load only this table
DB_TABLE=${DB_TABLE:-all}
if [[ "$DB_TABLE" == "all" ]]; then
    DB_DUMP=db/dump.sql
    # Get the name of the database that was dumped
    DUMP_DB_NAME=$(grep "CREATE DATABASE" "$DB_DUMP" | awk -F '`' '{print $2}')
    check_dump_file
    echo "Loading from $DB_DUMP to $DB_NAME."
    echo "Replacing database name in dump $DUMP_DB_NAME to $DB_NAME."

    BACKUP_FILE=db/$DB_NAME.${DATE}.sql
    echo "Making backup of $DB_NAME to $BACKUP_FILE"
    mysqldump --opt -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASSWORD" --databases "$DB_NAME" > "$BACKUP_FILE"

    echo "Loading dump into $DB_NAME"
    sed "s/$DUMP_DB_NAME/$DB_NAME/" $DB_DUMP \
        | mysql -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASSWORD" "$DB_NAME"
    echo "Loaded dump into $DB_NAME OK!"
else
    DB_DUMP=db/dump-$DB_TABLE.sql
    check_dump_file
    echo "Loading from $DB_DUMP to $DB_NAME.$DB_TABLE"

    BACKUP_FILE=db/$DB_NAME-$DB_TABLE.${DATE}.sql
    echo "Making backup of $DB_NAME.$DB_TABLE to $BACKUP_FILE"
    mysqldump --opt -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" "$DB_TABLE"> "$BACKUP_FILE"

    echo "Loading dump into $DB_NAME.$DB_TABLE"
    mysql -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" < "$DB_DUMP"
    echo "Loaded dump into $DB_NAME.$DB_TABLE OK!"
fi
